#ifndef CONSTANTS_H
#define CONSTANTS_H

constexpr auto ERROR_STARTUP_CONNECTION_FAILED = -1;
constexpr auto ERROR_STARTUP_ADDING_ENDPOINTS_FAILED = -2;
constexpr auto ERROR_STARTUP_FRAMETRIGGER_SETUP_FAILED = -3;

constexpr auto STARTUP_CONNECTION_ATTEMPS = 5;
constexpr auto STARTUP_CONNECTION_PAUSE_TIME = 500;

constexpr auto RADAR_MEASUREMENT_PAUSE_TIME = 100;

#endif // CONSTANTS_H
