#ifndef CONSTANTS_H
#define CONSTANTS_H

constexpr auto ERROR_STARTUP_CONNECTION_FAILED = -1;

constexpr auto STARTUP_CONNECTION_ATTEMPS = 5;
constexpr auto STARTUP_CONNECTION_PAUSE_TIME = 500;

constexpr auto RADAR_MEASUREMENT_PAUSE_TIME = 250;
constexpr auto RADAR_MEASUREMENT_AMOUNT_OF_RESET_CYCLES = 1000;

#endif // CONSTANTS_H
